### ISSUE TITLE
Error on auth-code and code commands

### ISSUE THREAD

**Issue by Stilic** [wh0/snail-cli#10]
When I running `snail auth send-email` for the first time, it's work fine. I have received the auth code email from Glitch. But, when I login using the code with `snail auth code`, it's say this:
```
Error: Glitch auth email response 404 not ok
    at Command.doAuthCode (/usr/pnpm-global/5/node_modules/.pnpm/glitch-snail@2.3.0/node_modules/glitch-snail/src/index.js:360:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)
```
How I can fix this issue?

**Comment by wh0** [comment]
I just tried this send-email + code signin flow, and it was working okay

```
app@snail-cli:~ 17:01 
$ snail auth send-email [redacted]

app@snail-cli:~ 17:01 
$  snail auth code [redacted]

app@snail-cli:~ 17:02 
$ snail whoami
[redacted]
```

however, I find that passing the wrong code or passing a code that has already been used gives a 404 like the one you've experienced:

```
app@snail-cli:~ 17:03 
$ snail auth code fake-fake-fake
Error: Glitch auth email response 404 not ok
    at Command.doAuthCode (/app/src/index.js:366:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

can you think of anything that might have messed up the code between the email and the terminal?

**Comment by Stylix58** [comment]
Yes, maybe.

**Comment by Yonle** [comment]
So i also analyzed this issue. So this issue only happing when **you request email magic code twice / multiple time**. So to solve this issue, **Try again later and request magic code again**.

**Comment by wh0** [comment]
Stilic, I haven't heard back from you, so I guess we'll leave it at "yes maybe."

Yonle, good point about Glitch's rate limiting on this.
