### ISSUE TITLE
`auth send-email` may soon require recaptcha

### ISSUE THREAD

**Issue by wh0** [wh0/snail-cli#11]
![image](https://user-images.githubusercontent.com/382796/128651407-d1b80f88-895f-4c3b-be59-425448e3e0c5.png)

They've added a recaptcha widget to the magic code form.

I tried going through the flow just now with Snail, but it was still working. But it may be a short matter of time before they add server-side verification of the recaptcha.

**Comment by khalby786** [comment]
> But it may be a short matter of time before they add server-side verification of the recaptcha.

Would it be possible to bypass this?

**Comment by Yonle** [comment]
I heard that there's a trick to solve this issue by getting ReCaptcha code from client localStorage then send it to server. But i didn't think that method will work like how NewPipe grabs ReCaptcha code

**Comment by wh0** [comment]
do you have any references on how newpipe does it?

**Comment by wh0** [comment]
I think this has just happened.

**Comment by wh0** [comment]
added a note on the website 💁

**Comment by wh0** [comment]
updated the instructions more thoroughly. that's all we can do
