### ISSUE TITLE
[Bug]: "please input right arguments"

### ISSUE THREAD

**Issue by Yonle** [wh0/snail-cli#15]
![Screenshot_2021_0830_193215](https://user-images.githubusercontent.com/63401712/131339430-f76a5dca-02d2-4244-a7d4-f6d62c25f3f6.png)
The title describe it at all. I can't do anything like auth, login, login into term, and something right that after the recent update.

**Comment by wh0** [comment]
could this be a different package that uses `snail` as a bin name? how did you install it?

**Comment by Yonle** [comment]
`npm install -g glitch-snail` like normal

**Comment by wh0** [comment]
it must have lower priority than some other package. like this one

https://github.com/demohi/snail/blob/1556e20af13b524613c6dad870a61c66674b5295/lib/config.js#L43

**Comment by Yonle** [comment]
Closing because i had headache after checking `/usr/lib/node_modules` lol
