### ISSUE TITLE
terminal disconnects on its own

### ISSUE THREAD

**Issue by wh0** [wh0/snail-cli#2]
When you're not on the Glitch website, the socket for the terminal gets closed after <1 minute.
There must be something else that the web version connects to, without which Glitch doesn't recognize the container as in use. Maybe the OT socket, dunno.

**Comment by Yonle** [comment]
Can bypassed by using `snail ot status`
But it would be great to merge `ot status` in `term` to solve this issue.

**Comment by Yonle** [comment]
But keep in mind that `ot status` will disconnected if you ran `refresh` on terminal

**Comment by wh0** [comment]
hm, glitch's own terminal page doesn't connect to the OT server. I wonder if that means the official web terminal would disconnect on its own too.

**Comment by wh0** [comment]
![image](https://user-images.githubusercontent.com/382796/130374509-5f788ad8-7a14-43ee-acbf-8a2060c71cbb.png)

from a test I did just now (sorry for the low contrast; the "reconnect" overlay had appeared), opening up the terminal page for a project without also opening the editor

this was from running

```sh
watch "echo $(date); date"
```

so the top line shows when the test started and the bottom line shows the last time (rounded to 2.0 sec) it was connected

the connection only lasted ~30 seconds. confirmed additionally that this wasn't purely a network failure, with the automatic reconnection after that taking 15+ seconds, which is consistent with Glitch having to start the project container anew.

now we know that

1. the behavior is consistent with the official Glitch web version
2. there's a workaround, as posted by Yonle above

at this point I'll probably go only as far as adding a note to the command's help entry about this.

**Comment by wh0** [comment]
note added in v2.6.0
